version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - "./elastic/elasticsearch1.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - elastic
      - ingress
    ports:
      - 9201:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - "./elastic/elasticsearch2.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - elastic
      - ingress

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - "./elastic/elasticsearch3.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - elastic
      - ingress

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS:  http://es01:9200
    ports:
      - 5701:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
      - ingress

  nginx:
      image: nginx:latest
      ports:
          - 8081:80
      volumes:
          - ${PWD}/nginx-config/:/etc/nginx/conf.d/
      command: /bin/bash -c "nginx -g 'daemon off;'"
      ulimits:
        nproc: 65535
      networks:
        - ingress

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  elastic:
  ingress: